### PR TITLE
groot/bench-opendata: fix task-7

### LINKED ISSUE #4: Possible bugs in Task 7
I have several doubts about the current implementation of Task 7.

The benchmark description says to plot "jets [...] that are not within 0.4 in ΔR of any lepton [...]", i.e., of any muon or electron. In math, this is equivalent to the following conditions, which are all equivalent among themselves (omitting the conditions on pt):

```
(1) {j \in Jets | \nexists l \in Leptons :    DeltaR(j, l) < 0.4 }
(2) {j \in Jets | (\nexists m \in Muons :     DeltaR(j, m) < 0.4) \and
                  (\nexists e \in Electrons : DeltaR(j, e) < 0.4) }
(3) {j \in Jets | (\forall m \in Muons :    DeltaR(j, m) >= 0.4) \and
                  (\forall e \in Electrons: DeltaR(j, e) >= 0.4) }
(4) {j \in Jets | \forall m \in Muons :     DeltaR(j, m) >= 0.4 } \intersect
    {j \in Jets | \forall e \in Electrons:  DeltaR(j, e) >= 0.4 }
```

The current implementations is based on `goodJets`, which, roughly speaking, implements the following (it is called once on with muons, once with electrons):

```
(5) { j \in Jets | \exists m \in Muons :    DeltaR(j, m) >= 0.4) }
(6) { j \in Jets | \exists e \in Electrons: DeltaR(j, e) >= 0.4) }
```

That isn't the same. (5) and (6) compute if there exists a good lepton; (1) through (4) compute if there exists no bad one.

I see two other problems: First, `goodJets` is used the following way:

```go
var (
	jets    []int
	muJets  = goodJets(jetPt, jetEta, jetPhi, muPt, muEta, muPhi)
	eleJets = goodJets(jetPt, jetEta, jetPhi, elePt, eleEta, elePhi)
)
switch {
case len(muJets) > 0:  // If there is one good jet as far as muons are concerned, electrons do not matter
	jets = muJets
case len(eleJets) > 0:
	jets = eleJets
default:
	continue
}
```

The problem is that the two types of leptons are never looked at jointly (like in formulation (3) above) and the results testing for each type are in no way combined (like in formulation (4) above). It seems like one of the two is necessary to compute the correct result.

Second, `goodMuon` may return the index of the same jet several times. This is the relevant part:

```go
var jets = make([]int, 0, len(pt1))

for ijet, jetPt := range pt1 {
	// ...
	for ilep, lepPt := range pt2 {
		// ...
		dr2 := ...
		if dr2 > dr2Min {
			jets = append(jets, ijet)
			// After we added ijet, we continue with the next lepton,
			// which might meet the condition again,
			// in which case ijet is added again
		}
	}
},
```

### PR DESCRIPTION
**Pull request by sbinet**
- consider all leptons as a whole
- correct isolation criteria

Fixes go-hep/examples#4.

### CODE REVIEW

**Comment by ingomueller-net** [comment]
Thanks for the fast reply and fix! The code looks good to me (but I learned Go just for the purpose of running this benchmark, so don't trust me). I did confirm that the resulting histogram is exactly the same as three other implementations: (1) mine in Go, (2) the [Coffea](https://github.com/mat-adamec/coffea-benchmarks/blob/master/benchmarks/example7.ipynb) implementation, (3) one I am writing in SQL.

**Comment by sbinet** [comment]
cool!

(out of curiosity, how was learning Go? would you recommand it for other HEP/astro/... scientists?)

**Comment by ingomueller-net** [comment]
I found it at least fairly readable; most of my "learning" consisted of guessing what your code does. It also seems pretty concise. I don't know about performance, which is probably one aspect scientists care about. Also, as a researcher in database systems, I think that SQL might be a good (better?) choice ;)

**Comment by sbinet** [comment]
thanks.

> Also, as a researcher in database systems, I think that SQL might be a good (better?) choice ;)

that last statement may be a bit biased :P
at least it isn't the same than mine.
even if I did dabble into those waters:
- https://github.com/go-hep/examples/blob/master/groot/bench-opendata/01-rsql.go
- https://godoc.org/go-hep.org/x/hep/groot/rsql#example-ScanH1D--WithH1D

(so once you have rewritten all these examples into a set of fancy SQL queries, you could do the same with `groot/rsql` :P)

**Comment by ingomueller-net** [comment]
Yes, I suspect so :) Thanks a lot for the pointers, I'll take a look! May I ask why you abandonded that direction? Why is SQL not suited?

**Comment by sbinet** [comment]
SQL is fine but a bit verbose for "Joe the physicist".
@jpivarski has been working on creating an SQL-like language more (better?) tailored at the kind of work HEP people do:
- https://github.com/jpivarski/PartiQL

**Comment by jpivarski** [comment]
PartiQL was an experiment with the idea of an SQL model (collection of tables with different lengths, related to one another through foreign keys) applied to _each event_ of a physics dataset. When an SQL model is applied to whole datasets (i.e. a "table of events") then it's possible to express HEP queries, but extremely cumbersome because every query is a "join on eventId" as we're never interested in relating quantities from one event to another event, and the handling of combinatorics of particles within an event gets intricate. [This question I asked 4 years ago](https://stackoverflow.com/q/38831961/1623645) convinced me that the SQL model is inappropriate for HEP datasets.

However, applying an SQL model to each event of a HEP dataset does make some sense: each particle collection (e.g. jets, muons, ...) has a different number of rows and possibly different columns for attributes, so each particle collection in one event is an SQL table. We have connections between these tables using foreign keys, usually row number for a particular sorting of the tables—this is a surrogate key.

This event-as-database was Gordon Watts's idea, which he is developing as [func_adl](https://github.com/iris-hep/func_adl). PartiQL was my experiment with the idea: it was originally going to be SQL syntax, but real SQL was still too cumbersome (we _always_ want to join on these surrogate keys, never any natural keys), so only a few keywords like `JOIN` are derived from SQL. It's also being more seriously developed by Lindsey Gray as [AwkwardQL](https://github.com/lgray/AwkwardQL).

Finally, if we do go the event-as-database route, it would be an entirely different database implementation from what's out there. Most databases are optimized for big tables; this would have to be optimized for many little tables, as the number of particles per event is 0‒2 for some particle types. Instead of a table with a billion rows, we have a billion tables with maybe 1 row. Time complexity for each operation (i.e. _O(n)_ vs _O(log(n))_ where _n_ is the number of elements in a table; the number that participate in a join) becomes much less important than setup and tear-down times when iterating from one event (collection of tables) to the next. It's an unusual problem that would require unusual solutions.

Surely I'm digressing from the focus of this PR, though...

**Pull request merged**
